// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnFJblczwQKCU-O849_4oywzLlg1mYa9M',
    appId: '1:106853218491:web:30b16bc9ea71913472d19e',
    messagingSenderId: '106853218491',
    projectId: 'pilot-flutter-anushua',
    authDomain: 'pilot-flutter-anushua.firebaseapp.com',
    storageBucket: 'pilot-flutter-anushua.appspot.com',
    measurementId: 'G-J3H3SH0PP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtdayRCWcoKGJZ37swJaHXEDdwl8mGYg',
    appId: '1:106853218491:android:e4d0b1f760803e7772d19e',
    messagingSenderId: '106853218491',
    projectId: 'pilot-flutter-anushua',
    storageBucket: 'pilot-flutter-anushua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv7UPHOfzGQ7himMZRsEGh9WeyrkZaCAo',
    appId: '1:106853218491:ios:ddc64f79bdd0203f72d19e',
    messagingSenderId: '106853218491',
    projectId: 'pilot-flutter-anushua',
    storageBucket: 'pilot-flutter-anushua.appspot.com',
    iosBundleId: 'com.aruksa.pilot',
  );
}
